import type { Metadata } from 'next';
import { Hero } from '@/components/Hero';
import { Features } from '@/components/Features';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Landing Page',
  description: 'Generated by PageCraft',
};

export default function Page() {
  return (
    <main className="min-h-screen">
      <Hero />
      <Features />
      <Footer />
    </main>
  );
}
