import type { GeneratedProject } from './types';
import type { StitchDesign, StitchElement, StitchStyle } from './schema';
import { StitchDesignSchema } from './schema';
import { generatePackageJson } from './templates/package-json';
import { generateTailwindConfig } from './templates/tailwind-config';
import { generateReadme } from './templates/readme';

export function generateNextJsCode(stitchDesignData: unknown): GeneratedProject {
  // Validate input with Zod
  const stitchDesign = StitchDesignSchema.parse(stitchDesignData);

  const files: GeneratedProject['files'] = [];

  // Extract top-level sections
  const components = extractComponents(stitchDesign.elements);

  // Generate components
  components.forEach(({ name, element }) => {
    const componentCode = generateComponent(name, element, stitchDesign);
    files.push({
      path: `components/${name}.tsx`,
      content: componentCode,
    });
  });

  // Generate main page
  const pageCode = generatePageComponent(stitchDesign.elements, components.map(c => c.name));
  files.push({
    path: 'app/page.tsx',
    content: pageCode,
  });

  // Generate config files
  files.push({
    path: 'tailwind.config.js',
    content: generateTailwindConfig(stitchDesign.theme),
  });

  files.push({
    path: 'package.json',
    content: generatePackageJson(),
  });

  files.push({
    path: 'README.md',
    content: generateReadme(),
  });

  // Generate root layout
  files.push({
    path: 'app/layout.tsx',
    content: generateRootLayout(),
  });

  // Generate globals.css
  files.push({
    path: 'app/globals.css',
    content: generateGlobalsCss(),
  });

  return { files };
}

interface ExtractedComponent {
  name: string;
  element: StitchElement;
}

function extractComponents(elements: StitchElement[]): ExtractedComponent[] {
  const components: ExtractedComponent[] = [];

  for (const element of elements) {
    // Extract recognizable component types
    if (element.type === 'hero') {
      components.push({ name: 'Hero', element });
    } else if (element.type === 'features') {
      components.push({ name: 'Features', element });
    } else if (element.type === 'footer') {
      components.push({ name: 'Footer', element });
    } else if (element.type === 'header') {
      components.push({ name: 'Header', element });
    }
  }

  return components;
}

function generatePageComponent(elements: StitchElement[], componentNames: string[]): string {
  const imports = componentNames.map(name => `import { ${name} } from '@/components/${name}';`).join('\n');

  const componentTags = componentNames.map(name => `      <${name} />`).join('\n');

  return `import type { Metadata } from 'next';
${imports}

export const metadata: Metadata = {
  title: 'Landing Page',
  description: 'Generated by PageCraft',
};

export default function Page() {
  return (
    <main className="min-h-screen">
${componentTags}
    </main>
  );
}
`;
}

function generateComponent(name: string, element: StitchElement, design: StitchDesign): string {
  const jsx = elementToJSX(element, 2);

  // Determine if component needs "use client"
  const needsClient = hasInteractivity(element);
  const clientDirective = needsClient ? '"use client";\n\n' : '';

  // Check if we need Link import
  const needsLink = hasLinks(element);
  const linkImport = needsLink ? 'import Link from \'next/link\';\n\n' : '';

  return `${clientDirective}${linkImport}export function ${name}() {
  return (
${jsx}
  );
}
`;
}

function hasLinks(element: StitchElement): boolean {
  if (element.type === 'button' && element.props?.href) {
    return true;
  }
  if (element.children) {
    return element.children.some(hasLinks);
  }
  return false;
}

function hasInteractivity(element: StitchElement): boolean {
  if (element.type === 'button' && element.props?.href) {
    return false; // Link buttons don't need client
  }
  if (element.type === 'button') {
    return true; // Interactive buttons need client
  }
  if (element.children) {
    return element.children.some(hasInteractivity);
  }
  return false;
}

function elementToJSX(element: StitchElement, indent: number = 0): string {
  const indentStr = '  '.repeat(indent);
  const childIndentStr = '  '.repeat(indent + 1);

  const tag = elementToHtmlTag(element);
  const className = styleToTailwind(element.style);
  const attrs = propsToAttributes(element);

  const openTag = `${indentStr}<${tag}${className ? ` className="${className}"` : ''}${attrs}>`;

  if (element.type === 'text' || element.type === 'heading') {
    const text = element.props?.text || '';
    return `${openTag}${text}</${tag}>`;
  }

  if (element.type === 'image') {
    const src = element.props?.src || '/placeholder.jpg';
    const alt = element.props?.alt || '';
    const width = extractNumber(element.style?.width) || 800;
    const height = extractNumber(element.style?.height) || 600;

    // Note: Image component import will be added to components that use it
    return `${indentStr}<img
${childIndentStr}src="${src}"
${childIndentStr}alt="${alt}"
${childIndentStr}width="${width}"
${childIndentStr}height="${height}"
${childIndentStr}className="${className}"
${indentStr}/>`;
  }

  if (element.type === 'button') {
    const text = element.props?.text || 'Click me';
    const href = element.props?.href;

    if (href) {
      return `${indentStr}<Link href="${href}" className="${className}">
${childIndentStr}${text}
${indentStr}</Link>`;
    }

    return `${openTag}
${childIndentStr}${text}
${indentStr}</${tag}>`;
  }

  if (!element.children || element.children.length === 0) {
    return `${openTag}</${tag}>`;
  }

  const childrenJSX = element.children
    .map(child => elementToJSX(child, indent + 1))
    .join('\n');

  return `${openTag}
${childrenJSX}
${indentStr}</${tag}>`;
}

function elementToHtmlTag(element: StitchElement): string {
  const typeMap: Record<string, string> = {
    container: 'div',
    section: 'section',
    header: 'header',
    footer: 'footer',
    hero: 'section',
    features: 'section',
    text: 'p',
    heading: 'h1',
    button: 'button',
    image: 'img',
    div: 'div',
  };

  return typeMap[element.type] || 'div';
}

function styleToTailwind(style?: StitchStyle): string {
  if (!style) return '';

  const classes: string[] = [];

  // Layout
  if (style.layout === 'flex') {
    classes.push('flex');
    if (style.flexDirection === 'column') classes.push('flex-col');
    if (style.justifyContent) classes.push(justifyToTailwind(style.justifyContent));
    if (style.alignItems) classes.push(alignToTailwind(style.alignItems));
    if (style.gap) classes.push(`gap-${style.gap}`);
  }

  if (style.layout === 'grid') {
    classes.push('grid');
    if (style.gap) classes.push(`gap-${style.gap}`);
  }

  // Colors
  if (style.backgroundColor) classes.push(colorToTailwind('bg', style.backgroundColor));
  if (style.textColor) classes.push(colorToTailwind('text', style.textColor));
  if (style.borderColor) classes.push(colorToTailwind('border', style.borderColor));

  // Typography
  if (style.fontSize) classes.push(fontSizeToTailwind(style.fontSize));
  if (style.fontWeight) classes.push(fontWeightToTailwind(style.fontWeight));

  // Spacing
  if (style.padding) classes.push(spacingToTailwind('p', style.padding));
  if (style.margin) classes.push(spacingToTailwind('m', style.margin));

  // Dimensions
  if (style.width) classes.push(dimensionToTailwind('w', style.width));
  if (style.height) classes.push(dimensionToTailwind('h', style.height));

  // Border radius
  if (style.borderRadius) classes.push(borderRadiusToTailwind(style.borderRadius));

  return classes.join(' ');
}

function justifyToTailwind(value: string): string {
  const map: Record<string, string> = {
    start: 'justify-start',
    center: 'justify-center',
    end: 'justify-end',
    between: 'justify-between',
    around: 'justify-around',
    evenly: 'justify-evenly',
  };
  return map[value] || '';
}

function alignToTailwind(value: string): string {
  const map: Record<string, string> = {
    start: 'items-start',
    center: 'items-center',
    end: 'items-end',
    stretch: 'items-stretch',
    baseline: 'items-baseline',
  };
  return map[value] || '';
}

function colorToTailwind(prefix: string, color: string): string {
  // Handle hex colors or color names
  if (color.startsWith('#')) {
    return `${prefix}-[${color}]`;
  }
  return `${prefix}-${color}`;
}

function fontSizeToTailwind(size: string): string {
  const map: Record<string, string> = {
    'xs': 'text-xs',
    'sm': 'text-sm',
    'base': 'text-base',
    'lg': 'text-lg',
    'xl': 'text-xl',
    '2xl': 'text-2xl',
    '3xl': 'text-3xl',
    '4xl': 'text-4xl',
    '5xl': 'text-5xl',
    '6xl': 'text-6xl',
  };
  return map[size] || `text-${size}`;
}

function fontWeightToTailwind(weight: string): string {
  const map: Record<string, string> = {
    'normal': 'font-normal',
    'medium': 'font-medium',
    'semibold': 'font-semibold',
    'bold': 'font-bold',
    'extrabold': 'font-extrabold',
  };
  return map[weight] || `font-${weight}`;
}

function spacingToTailwind(prefix: string, value: string): string {
  // Handle numeric values or Tailwind spacing scale
  const numMatch = value.match(/^(\d+)$/);
  if (numMatch) {
    return `${prefix}-${value}`;
  }
  return value;
}

function dimensionToTailwind(prefix: string, value: string): string {
  if (value === 'full') return `${prefix}-full`;
  if (value === 'screen') return `${prefix}-screen`;
  if (value === 'auto') return `${prefix}-auto`;
  return `${prefix}-[${value}]`;
}

function borderRadiusToTailwind(value: string): string {
  const map: Record<string, string> = {
    'none': 'rounded-none',
    'sm': 'rounded-sm',
    'md': 'rounded-md',
    'lg': 'rounded-lg',
    'xl': 'rounded-xl',
    'full': 'rounded-full',
  };
  return map[value] || `rounded-${value}`;
}

function propsToAttributes(element: StitchElement): string {
  const attrs: string[] = [];

  if (element.props?.id) {
    attrs.push(` id="${element.props.id}"`);
  }

  if (element.type === 'button' && element.props?.variant) {
    // Variant is handled via className
  }

  return attrs.join('');
}

function extractNumber(value?: string): number | undefined {
  if (!value) return undefined;
  const match = value.match(/(\d+)/);
  return match ? parseInt(match[1], 10) : undefined;
}

function generateRootLayout(): string {
  return `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PageCraft Generated Site',
  description: 'Generated by PageCraft AI',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`;
}

function generateGlobalsCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
}
