export function generateReadme(): string {
  return `# PageCraft Generated Site

This project was generated by [PageCraft](https://pagecraft.io) - an AI-powered landing page builder.

## Getting Started

First, install the dependencies:

\`\`\`bash
npm install
# or
yarn install
# or
pnpm install
\`\`\`

Then, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Project Structure

\`\`\`
.
├── app/
│   ├── layout.tsx       # Root layout
│   ├── page.tsx         # Main landing page
│   └── globals.css      # Global styles
├── components/
│   ├── Hero.tsx         # Hero section
│   ├── Features.tsx     # Features section
│   └── Footer.tsx       # Footer section
├── tailwind.config.js   # Tailwind configuration
└── package.json
\`\`\`

## Customization

### Colors

Edit the theme colors in \`tailwind.config.js\`:

\`\`\`js
colors: {
  primary: '#your-color',
  secondary: '#your-color',
  // ...
}
\`\`\`

### Components

All components are in the \`components/\` directory. Edit them to customize your site.

## Deployment

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new).

Check out the [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.

## Learn More

- [Next.js Documentation](https://nextjs.org/docs)
- [Tailwind CSS Documentation](https://tailwindcss.com/docs)
- [PageCraft](https://pagecraft.io)
`;
}
